server:
  port: 8881

spring:
  application:
    name: sts_auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yc-sts-db-auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: yc-sts-db-auth
    password: yc-sts-db-auth
#  messages:
#    basename: classpath*:i18n/messages
#    use-code-as-default-message: true
#    encoding: UTF-8
#    cache-duration: 3600
#    fallback-to-system-locale: false

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  global-config:
    db-config:
      # 逻辑删除配置删除前
      logic-not-delete-value: 0
      # 逻辑删除配置删除后
      logic-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:config/logback-spring.xml
  level:
    com.yaocode.sts.auth: INFO
    org.springframework: INFO
    org.apache.ibatis: debug
    org.springframework.context.support.ResourceBundleMessageSource: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
  file:
    path: ./logs

yaocode:
  database:
    migrate:
      sqlScriptPath:
        - classpath*:/db/migration/mysql/*.sql
  messages:
    i18n:
      enabled: true
#  web:
#    api:
#      elapsed:
#        enabled: false
  jwt:
    token:
      access:
        algorithm: HS512
        secret:  0123456789012345678901234567890123456789012345678901234567890123
        ttl: 3600

      refresh:
        algorithm: RS256
        public-key: ${JWT_REFRESH_PUBLIC_KEY}
        private-key: ${JWT_REFRESH_PRIVATE_KEY}
        ttl: 604800

      remember-me:
        algorithm: HS512
        public-key: ${JWT_REMEMBER_PUBLIC_KEY}
        private-key: ${JWT_REMEMBER_PRIVATE_KEY}
        ttl: 2592000

      state:
        algorithm: HS256
        secret: 9a2f8c4e6b1d7a3e5f0c9b2a4d6f1e8c3a5b7d9f2c4e6a8b0d2f4h6j8l0n2p4q
        ttl: 300
