<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.yaocode.sts.components.file</groupId>
        <artifactId>sts-components-file</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>sts-components-file-application</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>sts-components-file-application</name>
    <description>文件存储应用层 - 业务编排</description>

    <dependencies>
        <!-- 基础设施模块 -->
        <dependency>
            <groupId>com.yaocode.sts.components.file</groupId>
            <artifactId>sts-components-file-infrastructure</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
        </plugins>
    </build>
</project>