package com.yaocode.sts.auth.domain.enums;

import lombok.Getter;

/**
 * 领域事件类型枚举
 * 统一管理所有事件类型，避免硬编码字符串
 *
 * @author: Jin-LiangBo
 */
@Getter
public enum EventTypeEnums {

    // ===== UserAggregate 事件 (USER_) =====
    USER_REGISTERED("USER_REGISTERED", "用户注册"),
    USER_ACTIVATED("USER_ACTIVATED", "用户激活"),
    USER_DEACTIVATED("USER_DEACTIVATED", "用户停用"),
    USER_LOCKED("USER_LOCKED", "用户锁定"),
    USER_UNLOCKED("USER_UNLOCKED", "用户解锁"),
    USER_PASSWORD_CHANGED("USER_PASSWORD_CHANGED", "用户密码变更"),
    USER_PROFILE_UPDATED("USER_PROFILE_UPDATED", "用户档案更新"),
    USER_CONTACT_ADDED("USER_CONTACT_ADDED", "用户联系方式添加"),
    USER_CONTACT_REMOVED("USER_CONTACT_REMOVED", "用户联系方式移除"),
    USER_CONTACT_VERIFIED("USER_CONTACT_VERIFIED", "用户联系方式验证"),
    USER_ASSIGNED_TO_TENANT("USER_ASSIGNED_TO_TENANT", "用户分配租户"),
    USER_REMOVE_TENANT("USER_REMOVED_FROM_TENANT", "用户移除租户"),
    USER_ASSIGNED_ROLE("USER_ASSIGNED_ROLE", "用户分配角色"),
    USER_REMOVE_ROLE("USER_REMOVE_ROLE", "用户移除角色"),
    USER_ASSIGNED_TO_ORGANIZATION("USER_ASSIGNED_TO_ORGANIZATION", "用户分配组织"),
    USER_REMOVE_ORGANIZATION("USER_REMOVE_ORGANIZATION", "用户移除组织"),
    USER_ASSIGNED_TO_USER_GROUP("USER_ASSIGNED_TO_USER_GROUP", "用户分配用户组"),
    USER_REMOVED_FROM_USER_GROUP("USER_REMOVED_FROM_USER_GROUP", "用户移除用户组"),
    MFA_BOUND("MFA_BOUND", "MFA绑定"),
    MFA_UNBOUND("MFA_UNBOUND", "MFA解绑"),

    // ===== TenantAggregate 事件 (TENANT_) =====
    TENANT_CREATED("TENANT_CREATED", "租户创建"),
    TENANT_ACTIVATED("TENANT_ACTIVATED", "租户激活"),
    TENANT_SUSPENDED("TENANT_SUSPENDED", "租户停用"),
    USER_ADDED_TO_TENANT("USER_ADDED_TO_TENANT", "用户添加到租户"),
    USER_REMOVED_FROM_TENANT("USER_REMOVED_FROM_TENANT", "用户从租户移除"),
    TENANT_PASSWORD_POLICY_UPDATED("TENANT_PASSWORD_POLICY_UPDATED", "租户密码策略更新"),
    TENANT_SESSION_CONFIG_UPDATED("TENANT_SESSION_CONFIG_UPDATED", "租户会话配置更新"),
    TENANT_MFA_CONFIG_UPDATED("TENANT_MFA_CONFIG_UPDATED", "租户MFA配置更新"),
    TENANT_LOGIN_CONFIG_UPDATED("TENANT_LOGIN_CONFIG_UPDATED", "租户登录配置更新"),
    TENANT_BRAND_CONFIG_UPDATED("TENANT_BRAND_CONFIG_UPDATED", "租户品牌配置更新"),
    COMPANY_ADDED_TO_TENANT("COMPANY_ADDED_TO_TENANT", "公司添加到租户"),
    COMPANY_REMOVED_FROM_TENANT("COMPANY_REMOVED_FROM_TENANT", "公司从租户移除"),
    INSTANCE_ADDED_TO_TENANT("INSTANCE_ADDED_TO_TENANT", "实例添加到租户"),
    INSTANCE_REMOVED_FROM_TENANT("INSTANCE_REMOVED_FROM_TENANT", "实例从租户移除"),

    // ===== OrganizationInfoAggregate 事件 (ORG_) =====
    ORGANIZATION_CREATED("ORGANIZATION_CREATED", "组织创建"),
    ORGANIZATION_ENABLED("ORGANIZATION_ENABLED", "组织启用"),
    ORGANIZATION_DISABLED("ORGANIZATION_DISABLED", "组织禁用"),
    ORGANIZATION_MANAGER_CHANGED("ORGANIZATION_MANAGER_CHANGED", "组织负责人变更"),
    ORGANIZATION_ADDED_USER("ORGANIZATION_ADDED_USER", "用户添加到组织"),
    ORGANIZATION_REMOVE_USER("ORGANIZATION_REMOVE_USER", "用户从组织移除"),
    ORGANIZATION_ADD_USER_GROUP("ORGANIZATION_ADD_USER_GROUP", "用户组关联到组织"),
    ORGANIZATION_REMOVE_USER_GROUP("ORGANIZATION_REMOVE_USER_GROUP", "用户组从组织移除"),

    // ===== RoleInfoAggregate 事件 (ROLE_) =====
    ROLE_CREATED("ROLE_CREATED", "角色创建"),
    ROLE_ENABLED("ROLE_ENABLED", "角色启用"),
    ROLE_DISABLED("ROLE_DISABLED", "角色禁用"),
    RESOURCE_ASSIGNED_TO_ROLE("RESOURCE_ASSIGNED_TO_ROLE", "资源分配给角色"),
    RESOURCE_REMOVED_FROM_ROLE("RESOURCE_REMOVED_FROM_ROLE", "资源从角色移除"),
    USER_ASSIGNED_TO_ROLE("USER_ASSIGNED_TO_ROLE", "用户分配给角色"),
    USER_REMOVED_FROM_ROLE("USER_REMOVED_FROM_ROLE", "用户从角色移除"),
    USER_GROUP_ASSIGNED_TO_ROLE("USER_GROUP_ASSIGNED_TO_ROLE", "用户组分配给角色"),
    USER_GROUP_REMOVED_FROM_ROLE("USER_GROUP_REMOVED_FROM_ROLE", "用户组从角色移除"),
    RESOURCES_ASSIGNED_TO_ROLE("RESOURCES_ASSIGNED_TO_ROLE", "批量资源分配给角色"),
    USERS_ASSIGNED_TO_ROLE("USERS_ASSIGNED_TO_ROLE", "批量用户分配给角色"),

    // ===== ResourceInfoAggregate 事件 (RESOURCE_) =====
    RESOURCE_CREATED("RESOURCE_CREATED", "资源创建"),
    RESOURCE_ENABLED("RESOURCE_ENABLED", "资源启用"),
    RESOURCE_DISABLED("RESOURCE_DISABLED", "资源禁用"),
    RESOURCE_DEPRECATED("RESOURCE_DEPRECATED", "资源标记废弃"),
    RESOURCE_UNDEPRECATED("RESOURCE_UNDEPRECATED", "资源取消废弃"),
    RESOURCE_ADDED_TO_WHITE_LIST("RESOURCE_ADDED_TO_WHITE_LIST", "资源加入白名单"),
    RESOURCE_REMOVED_FROM_WHITE_LIST("RESOURCE_REMOVED_FROM_WHITE_LIST", "资源移出白名单"),
    RESOURCE_UPGRADED("RESOURCE_UPGRADED", "资源升级"),

    // ===== UserGroupAggregate 事件 (GROUP_) =====
    USER_GROUP_CREATED("USER_GROUP_CREATED", "用户组创建"),
    USER_GROUP_ENABLED("USER_GROUP_ENABLED", "用户组启用"),
    USER_GROUP_DISABLED("USER_GROUP_DISABLED", "用户组禁用"),
    USER_ADDED_TO_GROUP("USER_ADDED_TO_GROUP", "用户添加到用户组"),
    USER_REMOVED_FROM_GROUP("USER_REMOVED_FROM_GROUP", "用户从用户组移除"),
    ROLE_BOUND_TO_GROUP("ROLE_BOUND_TO_GROUP", "角色绑定到用户组"),
    ROLE_UNBOUND_FROM_GROUP("ROLE_UNBOUND_FROM_GROUP", "角色从用户组解绑"),

    // ===== ClientAggregate 事件 (CLIENT_) =====
    CLIENT_CREATED("CLIENT_CREATED", "客户端创建"),
    CLIENT_ENABLED("CLIENT_ENABLED", "客户端启用"),
    CLIENT_DISABLED("CLIENT_DISABLED", "客户端禁用"),
    CLIENT_SECRET_ROTATED("CLIENT_SECRET_ROTATED", "客户端密钥轮换"),
    GRANT_TYPE_ADDED("GRANT_TYPE_ADDED", "授权类型添加"),
    GRANT_TYPE_REMOVED("GRANT_TYPE_REMOVED", "授权类型移除");

    private final String code;
    private final String desc;

    EventTypeEnums(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    @Override
    public String toString() {
        return code;
    }
}
