package com.yaocode.sts.file.core.enums;

import com.yaocode.sts.file.core.constants.FileI18nKeyConstants;
import lombok.Getter;

/**
 * 文件服务错误码枚举
 * <p>
 * 错误码格式: 模块(2位) + 分类(2位) + 序号(2位)
 * </p>
 *
 * @author Jin-LiangBo
 * @date 2025年10月08日 17:53
 */
@Getter
public enum FileErrorCodeEnums {

    // ==================== 文件错误 (10-29) ====================
    FILE_UPLOAD_ERROR("100000", FileI18nKeyConstants.FILE_UPLOAD_ERROR),
    FILE_NOT_FOUND("100001", FileI18nKeyConstants.FILE_NOT_FOUND),
    FILE_EMPTY("100002", FileI18nKeyConstants.FILE_EMPTY),
    FILE_TOO_LARGE("100003", FileI18nKeyConstants.FILE_TOO_LARGE),
    FILE_SIZE_INVALID("100004", FileI18nKeyConstants.FILE_SIZE_INVALID),
    FILE_NAME_EMPTY("100005", FileI18nKeyConstants.FILE_NAME_EMPTY),
    FILE_NAME_INVALID("100006", FileI18nKeyConstants.FILE_NAME_INVALID),
    FILE_ALREADY_EXISTS("100007", FileI18nKeyConstants.FILE_ALREADY_EXISTS),
    FILE_HASH_MISMATCH("100008", FileI18nKeyConstants.FILE_HASH_MISMATCH),
    FILE_EXTENSION_NOT_ALLOWED("100009", FileI18nKeyConstants.FILE_EXTENSION_NOT_ALLOWED),
    FILE_READ_FAILED("100010", FileI18nKeyConstants.FILE_READ_FAILED),
    FILE_WRITE_FAILED("100011", FileI18nKeyConstants.FILE_WRITE_FAILED),
    FILE_DELETE_FAILED("100012", FileI18nKeyConstants.FILE_DELETE_FAILED),
    FILE_CONTENT_UNCHANGED("100013", FileI18nKeyConstants.FILE_CONTENT_UNCHANGED),
    FILE_METADATA_UPDATE_FAILED("100014", FileI18nKeyConstants.FILE_METADATA_UPDATE_FAILED),
    FILE_PREPARE_FAILED("100015", FileI18nKeyConstants.FILE_PREPARE_FAILED),

    // ==================== 上传错误 (30-49) ====================
    UPLOAD_FAILED("103001", FileI18nKeyConstants.UPLOAD_FAILED),
    UPLOAD_INTERRUPTED("103002", FileI18nKeyConstants.UPLOAD_INTERRUPTED),
    UPLOAD_TIMEOUT("103003", FileI18nKeyConstants.UPLOAD_TIMEOUT),
    UPLOAD_SESSION_NOT_FOUND("103004", FileI18nKeyConstants.UPLOAD_SESSION_NOT_FOUND),
    UPLOAD_SESSION_EXPIRED("103005", FileI18nKeyConstants.UPLOAD_SESSION_EXPIRED),
    UPLOAD_SESSION_COMPLETED("103006", FileI18nKeyConstants.UPLOAD_SESSION_COMPLETED),
    UPLOAD_CHUNK_MISSING("103007", FileI18nKeyConstants.UPLOAD_CHUNK_MISSING),
    UPLOAD_CHUNK_MD5_MISMATCH("103008", FileI18nKeyConstants.UPLOAD_CHUNK_MD5_MISMATCH),
    UPLOAD_CHUNK_ALREADY_EXISTS("103009", FileI18nKeyConstants.UPLOAD_CHUNK_ALREADY_EXISTS),
    UPLOAD_PREPARE_FAILED("103010", FileI18nKeyConstants.UPLOAD_PREPARE_FAILED),
    UPLOAD_CANCEL_FAILED("103011", FileI18nKeyConstants.UPLOAD_CANCEL_FAILED),

    // ==================== 下载错误 (50-69) ====================
    DOWNLOAD_FAILED("105001", FileI18nKeyConstants.DOWNLOAD_FAILED),
    DOWNLOAD_INTERRUPTED("105002", FileI18nKeyConstants.DOWNLOAD_INTERRUPTED),
    DOWNLOAD_TOKEN_INVALID("105003", FileI18nKeyConstants.DOWNLOAD_TOKEN_INVALID),
    DOWNLOAD_TOKEN_EXPIRED("105004", FileI18nKeyConstants.DOWNLOAD_TOKEN_EXPIRED),
    DOWNLOAD_RANGE_INVALID("105005", FileI18nKeyConstants.DOWNLOAD_RANGE_INVALID),
    DOWNLOAD_STREAM_FAILED("105006", FileI18nKeyConstants.DOWNLOAD_STREAM_FAILED),

    // ==================== 存储错误 (70-89) ====================
    STORAGE_ERROR("107000", FileI18nKeyConstants.STORAGE_ERROR),
    STORAGE_TYPE_NOT_SUPPORTED("107001", FileI18nKeyConstants.STORAGE_TYPE_NOT_SUPPORTED),
    STORAGE_NODE_NOT_FOUND("107002", FileI18nKeyConstants.STORAGE_NODE_NOT_FOUND),
    STORAGE_NODE_UNAVAILABLE("107003", FileI18nKeyConstants.STORAGE_NODE_UNAVAILABLE),
    STORAGE_CAPACITY_EXCEEDED("107004", FileI18nKeyConstants.STORAGE_CAPACITY_EXCEEDED),
    STORAGE_CONNECTION_FAILED("107005", FileI18nKeyConstants.STORAGE_CONNECTION_FAILED),
    STORAGE_UPLOAD_FAILED("107006", FileI18nKeyConstants.STORAGE_UPLOAD_FAILED),
    STORAGE_DOWNLOAD_FAILED("107007", FileI18nKeyConstants.STORAGE_DOWNLOAD_FAILED),
    STORAGE_DELETE_FAILED("107008", FileI18nKeyConstants.STORAGE_DELETE_FAILED),
    STORAGE_MIGRATE_FAILED("107009", FileI18nKeyConstants.STORAGE_MIGRATE_FAILED),
    STORAGE_ARCHIVE_FAILED("107010", FileI18nKeyConstants.STORAGE_ARCHIVE_FAILED),
    STORAGE_UNARCHIVE_FAILED("107011", FileI18nKeyConstants.STORAGE_UNARCHIVE_FAILED),
    STORAGE_HEALTH_CHECK_FAILED("107012", FileI18nKeyConstants.STORAGE_HEALTH_CHECK_FAILED),

    // ==================== 版本错误 (90-109) ====================
    VERSION_CREATE_DENIED("109001", FileI18nKeyConstants.VERSION_CREATE_DENIED),
    VERSION_NOT_FOUND("109002", FileI18nKeyConstants.VERSION_NOT_FOUND),
    VERSION_DELETE_DENIED("109003", FileI18nKeyConstants.VERSION_DELETE_DENIED),
    VERSION_TAG_EXIST("109004", FileI18nKeyConstants.VERSION_TAG_EXIST),
    VERSION_TAG_NOT_FOUND("109005", FileI18nKeyConstants.VERSION_TAG_NOT_FOUND),
    VERSION_BRANCH_NOT_FOUND("109006", FileI18nKeyConstants.VERSION_BRANCH_NOT_FOUND),
    VERSION_BRANCH_ALREADY_EXISTS("109007", FileI18nKeyConstants.VERSION_BRANCH_ALREADY_EXISTS),
    VERSION_BRANCH_DELETE_DENIED("109008", FileI18nKeyConstants.VERSION_BRANCH_DELETE_DENIED),
    VERSION_MERGE_CONFLICT("109009", FileI18nKeyConstants.VERSION_MERGE_CONFLICT),
    VERSION_ROLLBACK_FAILED("109010", FileI18nKeyConstants.VERSION_ROLLBACK_FAILED),
    VERSION_CONTROL_DISABLED("109011", FileI18nKeyConstants.VERSION_CONTROL_DISABLED),
    VERSION_ALREADY_LATEST("109012", FileI18nKeyConstants.VERSION_ALREADY_LATEST),
    VERSION_NO_COMMON_ANCESTOR("109013", FileI18nKeyConstants.VERSION_NO_COMMON_ANCESTOR),

    // ==================== 权限错误 (110-129) ====================
    PERMISSION_DENIED("110001", FileI18nKeyConstants.PERMISSION_DENIED),
    OVERWRITE_DENIED("110002", FileI18nKeyConstants.OVERWRITE_DENIED),
    DELETE_DENIED("110003", FileI18nKeyConstants.DELETE_DENIED),
    UNAUTHORIZED("110004", FileI18nKeyConstants.UNAUTHORIZED),
    FORBIDDEN("110005", FileI18nKeyConstants.FORBIDDEN),
    TENANT_MISMATCH("110006", FileI18nKeyConstants.TENANT_MISMATCH),

    // ==================== 策略错误 (130-149) ====================
    STRATEGY_NOT_SUPPORTED("130001", FileI18nKeyConstants.STRATEGY_NOT_SUPPORTED),
    STRATEGY_EXECUTION_FAILED("130002", FileI18nKeyConstants.STRATEGY_EXECUTION_FAILED),
    STRATEGY_NOT_FOUND("130003", FileI18nKeyConstants.STRATEGY_NOT_FOUND),
    DUPLICATE_STRATEGY_NOT_SUPPORTED("130004", FileI18nKeyConstants.DUPLICATE_STRATEGY_NOT_SUPPORTED),

    // ==================== 哈希错误 (150-169) ====================
    HASH_ALGORITHM_UNAVAILABLE("101500", FileI18nKeyConstants.HASH_ALGORITHM_UNAVAILABLE),
    HASH_MD5_UNAVAILABLE("101501", FileI18nKeyConstants.HASH_MD5_UNAVAILABLE),
    HASH_SHA_UNAVAILABLE("101502", FileI18nKeyConstants.HASH_SHA_UNAVAILABLE),
    HASH_SM3_UNAVAILABLE("101503", FileI18nKeyConstants.HASH_SM3_UNAVAILABLE),
    HASH_CALCULATE_FAILED("101504", FileI18nKeyConstants.HASH_CALCULATE_FAILED),
    HASH_FILE_NOT_VALID("101505", FileI18nKeyConstants.HASH_FILE_NOT_VALID),
    HASH_INPUT_STREAM_NULL("101506", FileI18nKeyConstants.HASH_INPUT_STREAM_NULL),
    HASH_DATA_EMPTY("101507", FileI18nKeyConstants.HASH_DATA_EMPTY),
    HASH_TEXT_EMPTY("101508", FileI18nKeyConstants.HASH_TEXT_EMPTY),

    // ==================== 应用层 - 文件管理 (102000-102029) ====================
    FILE_ALREADY_DELETED("102000", FileI18nKeyConstants.FILE_ALREADY_DELETED),
    FILE_ALREADY_ARCHIVED("102001", FileI18nKeyConstants.FILE_ALREADY_ARCHIVED),
    FILE_NOT_DELETED("102002", FileI18nKeyConstants.FILE_NOT_DELETED),
    FILE_EXPIRED("102003", FileI18nKeyConstants.FILE_EXPIRED),
    FILE_NOT_IN_RECYCLE_BIN("102004", FileI18nKeyConstants.FILE_NOT_IN_RECYCLE_BIN),
    FILE_ALREADY_AUDITED("102005", FileI18nKeyConstants.FILE_ALREADY_AUDITED),
    FILE_DOWNLOAD_ERROR("102006", FileI18nKeyConstants.FILE_DOWNLOAD_ERROR),

    // ==================== 应用层 - 存储节点 (102030-102039) ====================
    NODE_CODE_EXISTS("102030", FileI18nKeyConstants.NODE_CODE_EXISTS),
    STORAGE_NODE_DELETE_FAILED("102031", FileI18nKeyConstants.STORAGE_NODE_DELETE_FAILED),

    // ==================== 应用层 - 版本控制 (102040-102059) ====================
    BRANCH_ALREADY_EXISTS("102040", FileI18nKeyConstants.BRANCH_ALREADY_EXISTS),
    BRANCH_NOT_FOUND("102041", FileI18nKeyConstants.BRANCH_NOT_FOUND),
    BRANCH_NOT_SAME_FILE("102042", FileI18nKeyConstants.BRANCH_NOT_SAME_FILE),
    BRANCH_HEAD_NOT_FOUND("102043", FileI18nKeyConstants.BRANCH_HEAD_NOT_FOUND),
    SOURCE_BRANCH_NOT_FOUND("102044", FileI18nKeyConstants.SOURCE_BRANCH_NOT_FOUND),
    DEFAULT_BRANCH_NOT_FOUND("102045", FileI18nKeyConstants.DEFAULT_BRANCH_NOT_FOUND),
    CANNOT_DELETE_DEFAULT_BRANCH("102046", FileI18nKeyConstants.CANNOT_DELETE_DEFAULT_BRANCH),
    TAG_ALREADY_EXISTS("102047", FileI18nKeyConstants.TAG_ALREADY_EXISTS),
    TAG_NOT_FOUND("102048", FileI18nKeyConstants.TAG_NOT_FOUND),
    NO_COMMON_ANCESTOR("102049", FileI18nKeyConstants.NO_COMMON_ANCESTOR),
    ALREADY_LATEST_VERSION("102050", FileI18nKeyConstants.ALREADY_LATEST_VERSION),
    CURRENT_VERSION_NOT_FOUND("102051", FileI18nKeyConstants.CURRENT_VERSION_NOT_FOUND),
    VERSION_CONTROL_NOT_ENABLED("102052", FileI18nKeyConstants.VERSION_CONTROL_NOT_ENABLED),

    // ==================== 应用层 - 通用 (102060-102069) ====================
    STORAGE_OPERATION_FAILED("102060", FileI18nKeyConstants.STORAGE_OPERATION_FAILED),
    TARGET_STORAGE_SAME_AS_CURRENT("102061", FileI18nKeyConstants.TARGET_STORAGE_SAME_AS_CURRENT),
    DELETE_STORAGE_FILE_FAILED("102062", FileI18nKeyConstants.DELETE_STORAGE_FILE_FAILED),
    FILE_ARCHIVED_CANNOT_DELETE("102063", FileI18nKeyConstants.FILE_ARCHIVED_CANNOT_DELETE),
    ;

    private final String code;
    private final String msg;

    FileErrorCodeEnums(String code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    /**
     * 根据code获取枚举
     */
    public static FileErrorCodeEnums fromCode(String code) {
        if (code == null) {
            return null;
        }
        for (FileErrorCodeEnums e : values()) {
            if (e.code.equals(code)) {
                return e;
            }
        }
        return null;
    }

}